# Preface {.unnumbered}

The Kenya National Bureau of Statistics (KNBS) is mandated by the Statistics Act, Cap 112 to collect, compile, analyse, publish, and disseminate statistical information, and to coordinate the National Statistical System. As part of this mandate, the Bureau is responsible for promoting the use of standard concepts, definitions, classifications, and methodologies to enhance consistency and comparability of official statistics across the National Statistical System (NSS).

In its effort to undertake its role for standardization and ensure coordination and harmonization between data producers and users, the KNBS has developed a Compendium of Concepts and Definitions. The Compendium provides a list of concepts and definitions as used across the NSS, organized in line with the Classification of Statistical Activities (CSA) to cover various statistical domains such as population, economy, environment, and governance, among others.

Use of the Compendium by all actors in the National Statistical System will ensure adherence to common standards in data production and use, improved harmonization across statistical domains, and enhanced comparability of statistical outputs. In addition, it supports compliance with the provisions of the Kenya Statistical Quality Assurance Framework (KeSQAF), which promotes quality across the statistical value chain by emphasizing key dimensions such as relevance, accuracy, coherence, and accessibility.

We welcome all users across the NSS and beyond to use this document as a standard reference. Its consistent application will contribute to the production and use of high-quality, harmonized, and credible statistics to inform policy, planning, monitoring, and decision-making at all levels.


Macdonald G. Obudho, PhD, EBS, MBS
Director General